# Generated by Django 3.2.12 on 2023-06-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_auto_20220406_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='KruegerJobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Number')),
                ('jobquote', models.CharField(choices=[('Job', 'Job'), ('Quote', 'Quote')], max_length=100, verbose_name='Workorder or Quote')),
                ('company', models.CharField(choices=[('LK', 'Lk'), ('KRUEGER', 'Krueger')], max_length=100, verbose_name='Company')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Description')),
                ('set_per_book', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sets per Book')),
                ('pages_per_book', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Pages per Book')),
                ('qty_of_sheets', models.CharField(blank=True, max_length=10, null=True, verbose_name='Qty of Sheets')),
                ('original_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Size')),
                ('press_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Press Size')),
                ('press_size_per_parent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Press sheets / Parent')),
                ('flat_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Flat Size')),
                ('finished_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Finished Size')),
                ('gangup', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Gangup')),
                ('overage', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Overage')),
                ('output_per_sheet', models.CharField(blank=True, max_length=10, null=True, verbose_name='Output per Parent Sheet')),
                ('parent_sheets_required', models.CharField(blank=True, max_length=10, null=True, verbose_name='Parent Sheets Required')),
                ('side_1_clicks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Side 1 Clicks')),
                ('side_2_clicks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Side 2 Clicks')),
                ('paper_stock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paper Stock')),
                ('price_per_m', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price per M')),
                ('dateentered', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
