# Generated by Django 3.2.12 on 2023-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Job Description'),
        ),
    ]
