# Generated by Django 3.2.12 on 2023-06-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20230607_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_reclaim_artwork',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_workorder',
        ),
    ]
