# Generated by Django 3.2.12 on 2023-06-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20230607_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_insert_chip_divider',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_insert_frontback_cover',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_insert_wrap_around',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_set_folder',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_set_to_drill',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_set_to_staple',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_staple',
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='step_fold_price',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cost to Fold'),
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='step_number_price',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cost to Number'),
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='step_perf_price',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cost to Perf'),
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='step_staple_price',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cost to Staple'),
        ),
    ]
