# Generated by Django 3.2.12 on 2023-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20230607_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_bulk_mail_tray_sort_paperwork',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_count_package',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_delivery',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_fold',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_id_count',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_packing_slip',
        ),
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='step_tab_for_mailing',
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='step_tab_price',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cost to Tab for Mailing'),
        ),
    ]
