# Generated by Django 3.2.12 on 2023-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20230607_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='material_markup',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Material Markup Amount'),
        ),
    ]
