# Generated by Django 3.2.12 on 2023-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_kruegerjobdetail_material_markup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kruegerjobdetail',
            old_name='taps_price_per_tab',
            new_name='tabs_price_per_tab',
        ),
    ]
